credentials:
  usernames:
    esaid:
      email: emmanuel.said@gmail.com
      name: Emmanuel SAID
      password: $2b$12$QimDPK1Aw902Ak5JG8DxGu/m2UNafZiv2vFgK04cVVeniqgfaGGNa # 1234 To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$QimDPK1Aw902Ak5JG8DxGu/m2UNafZiv2vFgK04cVVeniqgfaGGNa  # 1234 To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
